name: Publish scripts 
on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: CreeperG16/onix-scripting-compiler
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.x

      - name: Build scripts
        run: node ./index.js --release
  
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push

      #- name: Commit changes
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: Update release scripts
